version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Installing CMAKE
          command: apt install -y cmake
      - run:
          name: Creating Build Files
          command: cmake -H. -Bbuild
      - run:
          name: Compiling
          command: cmake --build build
      - run:
          name: Installing
          command: cmake --install build
      - run:
          name: Testing
          command: cd build && make test
